[package]
name = "lua-patterns"
version = "0.1.0"
authors = ["steve donovan <steve.j.donovan@gmail.com>"]
links = "foo"
build = "build.rs"

[dependencies]
libc="0.2.0"

[build-dependencies]
gcc="0.3"


